leaguesite/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.ListGroups.as_view(), name="all"),
    path("new/", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<slug:slug>/", views.SingleGroup.as_view(), name="single"),
    path("join/<slug:slug>/", views.JoinGroup.as_view(), name="join"),
    path("leave/<slug:slug>/", views.LeaveGroup.as_view(), name="leave")
],

leaguesite/leaguesite/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/',include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('posts/', include('posts.urls', namespace="posts")),
    path('groups/', include('groups.urls', namespace="groups")),
]

leaguesite/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<pk>/", views.DeletePost.as_view(), name="delete")
]

leaguesite/groups/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from django.utils.text import slugify


from django.contrib.auth import get_user_model
User = get_user_model()


from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = m.html(self.description)
        super().save(*args,**kwargs)


    def get_absolute_url(self):
        return reverse('groups: single', kwargs={'slug':self.slug})
    

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group', 'user')


    pass

leaguesite/groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.urls import reverse
from django.shortcuts import get_object_or_404

from django.views import generic 
from groups.models import Group, GroupMember
from django.contrib import messages

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DeleteView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})
    
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        
        except:
            messages.warning(self.request,"Warning already amemeber")
        else:
            messages.success(self.request, "You are now a member!")

        return super().get(request,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        models = Group

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

leaguesite/groups/templates/groups/group_base.html
{% extends "accounts/base.html"%}

{%block content%}
    {% block pregroup%}{%endblock%}
    {% block group_contnet%}{%endblock%}
    {% block postgroup%}{%endblock%}

{%endblock%}

leaguesite/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html'%}

{% block pregroup%}
<h2>{{group.name}}</h2>
<h3>Total Members: {{group.members.count }}</h3>

{% if user in group.members.all%}
<a href="{%url 'groups:leave' slug=group.slug%}">Leave</a>

{%else%}
<a href="{%url 'groups:join' slug=group.slug%}">Join</a>
{%endif%}
{% endblock%}



{% block group_content%}
{% if group.posts.count == 0%}
<h2>Be first to post in this group</h2>

{% else%}

{% for post in group.posts.all%}
{%include "posts/_post.html"%}

{endfor}
{% endblock%}

leaguesite/groups/templates/groups/group_form.html
{% extends "groups/group_base.html"%}

{% load bootstrap5%}

{% block group_content%}
<h4>Create a new Group</h4>
<form method="post" id="groupForm" action="{% url 'groups:create'%}">
{% csrf_token%}
{%bootstrap_form form%}
<input type="submit" value="Create">
</form>

{% endblock%}

leaguesite/groups/templates/groups/group_list.html
{% extends "groups/group_base.html"%}

{% block pregroup%}
{% if user.is_authenicated%}
<h2>Welcome back 
<a href="{% url 'posts:for_user' username=user.username%}">@{{user.username}}</a>
</h2>
{%endif%}
<h2>Groups</h2>
<p>Welcome to the groups page</p>


{% if user.is_authenicated%}
<a href="{% url 'groups:create' %}">
    <span>Create New Group</span>
</a>

{% endif%}

{%endblock%}



{%block group_content%}
{% for group in object_list %}
<a href="{% url 'groups:single' slug=group.slug%}">

    <h3>{{group.name}}</h3>
    <div>
        {{group.description_html|safe}}
    </div>
    <div>
        <span>{{group.memebers.count}}</span>
        Memeber {{group.members.count|pluralize}}
    </div>
</a>
{% endfor%}

{%endblock%}