leaguesite/leaguesite/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/',include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('posts/', include('posts.urls', namespace="posts")),
    path('groups/', include('groups.urls', namespace="groups")),
]

leaguesite/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<pk>/", views.DeletePost.as_view(), name="delete")
]

leaguesite/posts/models.py
from django.db import models

from django.urls import reverse
# Create your models here.
from django.conf import settings


from groups.models import Group

from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__ (self):
        return self.message
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


    def get_absolutle_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username, 'pk':self.pk})
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

leaguesite/posts/views.py
from typing import Any
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy

from django.views import generic
from django.http import Http404, HttpRequest, HttpResponse
from braces.views import SelectRelatedMixin

from . import models

from . import forms

from django.contrib.auth import get_user_model

User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('posts').get(username_iexact=self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
        
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
    
class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        query = super().get_queryset()
        return query.filter(user__username__iexact=self.kwargs.get('username'))
    


class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)
    
    def delete(self, *args: str, **kwargs): 
        # messages.success(self.request,'Post Deleted')
        return super().delete(*args, **kwargs)

leaguesite/posts/templates/_post.html
<div>
    <h3>{{post.message_html|safe}}</h3>
    <strong>{{post.user.username}}</strong>
    <h5>
    <span><a href=" {url 'posts:form_user' username=post.user.username%}"></a></span>
    <time>
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk%}"></a>
    </time>
    </h5>
    <div>
        {% if user.is_authenicated and post.user == user%}
        <a href="{% url 'posts:delete' pk=posts.pk %}" title="delete"><span>Remove</span></a>

        {%endif%}
    </div>
</div>

leaguesite/posts/templates/post_base.html
{% extends accounts/base.html%}

{% block content%}
{%block prepost%}{%endblock%}
{%block post_content%}{%endblock%}
{%block post_post%}{%endblock%}


{%endblock%}

leaguesite/posts/templates/post_confirm_delete.html
{% extends posts/post_base.html%}

{% block content%}
<h3>Are you sure you want to delete this post?</h3>

<div>
    {% include "posts/_post.html" with post=object hide_delete=True%}
</div>

<form method="post">
{%csrf_token%}
<input type="submit" value="Confirm Delete">
<a href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
</form>

{%endblock%}

leaguesite/posts/templates/post_detail.html
{% extends "posts/post_base.html"%}



{% block post_content%}

<div>
    {%include "posts/_post.html"%}
</div>

{% endblock%}

leaguesite/posts/templates/post_form.html
{% extends "posts/post_base.html"%}

{%load bootstrap5%}


{% block post_content%}

<form method="post" id="postForm" action="{% url 'posts:create'%}">
    {%csrf_token%}
    {% bootstrap_form form%}
    <input type="submit" value="Post">
</form>

{% endblock%}

leaguesite/posts/templates/post_list.html
{% extends "posts/post_base.html"%}

{%load bootstrap5%}


{% block pre_post_content%}
{% if request.user.is_authenticated%}
<div>
    {% for member_group in get_user_groups%}
    <li><a href="{% url 'groups:single' slug=member_group.group.slug%}"></a></li>

    {%endfor%}
</div>

{%endif%}
<div>
    <h5>All Groups</h5>
    <ul>
        {% for other_group in get_other_groups%}
        <li><a href="{% url 'groups:single' slug=other_group.slug%}"></a></li>
        {%endfor%}
    </ul>
</div>

{% endblock%}



{% block post_content%}
{% for post in post_list%}
{%include posts/_post.html%}


{% endfor%}
{% endblock%}

leaguesite/posts/templates/user_post_list.html
{% extends "posts/post_base.html"%}



{% block prepost%}

<div>
    <h4>${{post_uer.username}}</h4>
</div>

{% endblock%}



{% block post_content%}
{% for post in post_list%}

{% include "posts/_post.html"%}
{%endfor%}
{% endblock%}